config/routes.rb
Rails.application.routes.draw do
  resources :physicians
  resources :patients
  resources :appointments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :physician
  belongs_to :patient
  delegate :name, :to => :physician, :allow_nil => true, :prefix => true
  delegate :name, :to => :patient, :allow_nil => true, :prefix => true
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :physicians, :through => :appointments
end

app/models/physician.rb
class Physician < ApplicationRecord
  has_many :appointments
  has_many :patients, :through => :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  def new
    @appointment = Appointment.new
  end

  def edit
  end

  def show
  end

  def index
    @appointments = Appointment.all.paginate(page: params[:page],per_page: 10)
  end

  def destroy
    @appointment.destroy
    redirect_to appointments_path
  end

  def create
    @appointment = Appointment.new(appointment_params)
    Rails.logger.info appointment_params.inspect
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:physician_id, :patient_id, :appointment_date)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  def new
    @patient = Patient.new
  end

  def edit
  end

  def show
  end

  def index
    @patients = Patient.all.paginate(page: params[:page],per_page: 10)
  end

  def destroy
    @patient.destroy
    redirect_to patients_path
  end

  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:name, :patient_id)
  end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: [:show, :edit, :update, :destroy]
  def new
    @physician = Physician.new
  end

  def edit
  end

  def show
  end

  def index
    @physicians = Physician.all.paginate(page: params[:page],per_page: 10)
  end

  def destroy
    @physician.destroy
    redirect_to physicians_path
  end

  def create
    @physician = Physician.new(physician_params)

    respond_to do |format|
      if @physician.save
        format.html { redirect_to @physician, notice: 'physician was successfully created.' }
        format.json { render :show, status: :created, location: @physician }
      else
        format.html { render :new }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @physician.update(physician_params)
        format.html { redirect_to @physician, notice: 'physician was successfully updated.' }
        format.json { render :show, status: :ok, location: @physician }
      else
        format.html { render :edit }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_physician
    @physician = Physician.find(params[:id])
  end

  def physician_params
    params.require(:physician).permit(:name, :physician_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/appointments/_form.html.erb
<h2 class="largeHeader">Appointments</h2>

<%= form_with(model: appointment, local: true) do |form|%>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this user from being saved:</h>
      <ul>
        <% appointment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :physician_id %>
    <%= form.select :physician_id, options_from_collection_for_select(Physician.all, "id", "name")%>
  </div>
  <div class="form-group">
    <%= form.label :patient_id %>
    <%= form.select :patient_id, options_from_collection_for_select(Patient.all, "id", "name")%>
  </div>

  <div class="form-group">
    <%= form.label :appointment_date %>
    <%= form.datetime_select :appointment_date%>
  </div>

  <%=form.submit "submit", class: "btn btn-primary"%>
<% end %>

app/views/appointments/edit.html.erb
<%=  render 'form', appointment: @appointment %>

app/views/appointments/index.html.erb
<div class="container">
  <h2>Appointments</h2>
  <%= link_to "New", new_appointment_path %><br>
  <%= will_paginate @appointment, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Patient Name</th>
        <th>Physician Name</th>
        <th>Appointment Date</th>

        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.patient_name %></td>
        <td><%= appointment.physician_name %></td>
        <td><%= appointment.appointment_date %></td>

        <td><%= link_to "Show",  appointment_path(appointment.id) %></td>
        <td><%= link_to "Edit",  edit_appointment_path(appointment.id) %></td>
        <td><%= link_to "Destroy", appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
      </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/appointments/new.html.erb
<%=  render 'form', appointment: @appointment %>

app/views/appointments/show.html.erb
<p><%= notice %></p>
<p> Patient Name: <%=@appointment.patient_name %></p>
<p> Physician Name: <%=@appointment.physician_name %></p>
<p> Appointment Time: <%=@appointment.appointment_date %></p>

<%= link_to "Back to Appointment List", appointments_path %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhysicianPatientAppointment</title>
    <%= csrf_meta_tag %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- app/views/layouts/application.html.erb - it will be common throughout application -->


  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <script type="text/javascript"src="http://tarruda.github.com/bootstrap-datetimepicker/assets/js/bootstrap-datetimepicker.pt-BR.js"></script>

</head>
<body>
   <div class="container">
  <%= yield %>
</div>
  </body>
</html>

app/views/patients/_form.html.erb
<h2 class="largeHeader">Patients</h2>

<%= form_with(model: patient, local: true) do |form|%>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this user from being saved:</h>
      <ul>
        <% patient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :patient_name %>
    <%= form.text_field :name %>
  </div>

  <%=form.submit "submit", class: "btn btn-primary"%>
<% end %>

app/views/patients/edit.html.erb
<%=  render 'form', patient: @patient %>

app/views/patients/index.html.erb
<div class="container">
  <h2>Patients</h2>
  <%= link_to "New", new_patient_path %><br>
  <%= will_paginate @patient, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Patient Name</th>

        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>


        <td><%= link_to "Show",  patient_path(patient.id) %></td>
        <td><%= link_to "Edit",  edit_patient_path(patient.id) %></td>
        <td><%= link_to "Destroy", patient, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
      </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/patients/new.html.erb
<%=  render 'form', patient: @patient %>

app/views/patients/show.html.erb
<p><%= notice %></p>
<p> Patient Name: <%=@patient.name %></p>
<% @patient.appointments.each do |appointment| %>
<p> Appointment date: <%=appointment.appointment_date %></p>
<% end %>

<% @patient.physicians.each do |physician| %>
<p> Physician: <%=physician.name %></p>
<% end %>

<%= link_to "Back to Appointment List", patients_path %><br>

app/views/physicians/_form.html.erb
<h2 class="largeHeader">Physicians</h2>

<%= form_with(model: physician, local: true) do |form|%>
  <% if physician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(physician.errors.count, "error") %> prohibited this user from being saved:</h>
      <ul>
        <% physician.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name%>
  </div>

  <%=form.submit "submit", class: "btn btn-primary"%>
<% end %>

app/views/physicians/edit.html.erb
<%=  render 'form', physician: @physician %>

app/views/physicians/index.html.erb
<div class="container">
  <h2>Physicians</h2>
  <%= link_to "New", new_physician_path %><br>
  <%= will_paginate @physician, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Physician Name</th>

        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @physicians.each do |physician| %>
      <tr>
        <td><%= physician.name %></td>

        <td><%= link_to "Show",  physician_path(physician.id) %></td>
        <td><%= link_to "Edit",  edit_physician_path(physician.id) %></td>
        <td><%= link_to "Destroy", physician, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
      </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/physicians/new.html.erb
<%=  render 'form', physician: @physician %>

app/views/physicians/show.html.erb
<p><%= notice %></p>
<p> Physician Name: <%=@physician.name %></p>
<% @physician.appointments.each do |appointment| %>
<p> Appointment ID: <%=appointment.id %></p>
<% end %>

<% @physician.patients.each do |patient| %>
<p> Patient Name: <%=patient.name %></p>
<% end %>



<%= link_to "Back to Physicians List", physicians_path %><br>